// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { configDotenv } from "dotenv";
import { defineConfig } from "prisma/config";
configDotenv()

console.log(process.env.DB_URL)
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DB_URL,
  },

});
